### ISSUE TITLE
Error thrown when initiating NEW-PSSession to Centos Linux

### ISSUE THREAD

**Issue by energizedtech** [PowerShell/psl-omi-provider#32] opened 2016-10-12 02:15 UTC
Clean compile of OMI and PSL-OMI-Provider
Providing userid of root and matching password when prompted for Get-Credential on Windows.

PS D:> $o=New-PSSessionOption -SkipCACheck -SkipRevocationCheck -SkipCNCheck
PS D:> New-PSSession -Computername 10.254.0.130 -Credential $c -Authentication basic -UseSSL -SessionOption $o
New-PSSession : The type initializer for 'System.Management.Automation.ConfigPropertyAccessor' threw an exception.
At line:1 char:1
- New-PSSession -Computername 10.254.0.130 -Credential $c -Authenticati ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], RemoteException
  - FullyQualifiedErrorId : PSSessionOpenFailed

**Comment by energizedtech** [comment] 2016-10-12 02:16
Windows 10 PowerShell 5 as Client connecting to PowerShell on CentOS Linux

**Comment by andschwa** [comment] 2016-10-12 02:18
PowerShell version? Try building the Linux one from master.

**Comment by energizedtech** [comment] 2016-10-12 13:40
I just redid the process with Ubuntu, didn't re-compile from GitHub.  Exact same error

**Comment by energizedtech** [comment] 2016-10-12 13:41
In both cases the Calling Workstation (Windows 10 x64)

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by energizedtech** [comment] 2016-10-12 13:42
When you say rebuild are you referring to OMI, PSRP or POWERSHELL on Linux?

**Comment by energizedtech** [comment] 2016-10-12 13:43
For authentication should it be
root@ipaddress or simply root ?

**Comment by energizedtech** [comment] 2016-10-12 14:37
Running OMI regression test now...

**Comment by energizedtech** [comment] 2016-10-12 15:07
Just added PowerShell 6.0 to the equation on Windows 10

**Comment by andschwa** [comment] 2016-10-12 18:00
> When you say rebuild are you referring to OMI, PSRP or POWERSHELL on Linux?

Sorry, yes I mean PowerShell on Linux.

> For authentication should it be root@ipaddress or simply root ?

It should be just the user, `root`.

> New-PSSession : The type initializer for 'System.Management.Automation.ConfigPropertyAccessor' threw an exception.

This is an error we've previously resolved, but has not yet made it into releases. There were two parts:

1) The PSRP provider was not properly impersonating the expected user, so it would start PowerShell with `HOME=/root` (the home of root, the user that launched the OMI daemon since it's a service) but run with the user rights of `someuser` which could not read/write to `/root`. In https://github.com/PowerShell/psl-omi-provider/pull/31 I fixed the PSRP provider to set `HOME` to the home of the user being impersonated, to avoid this permission issue. I don't know if it's in the current package.

2) PowerShell would crash on start-up because of a regression that required the `HOME` directory to be readable. This was fixed in https://github.com/PowerShell/PowerShell/pull/2387, which I know didn't make into the alpha.10 release.

> Just added PowerShell 6.0 to the equation on Windows 10

I would not do this, it's an extra variable. No work has been done to ensure that PowerShell Core 6.0 remoting works (I mean, I *think* it does, but I've not personally tested it).

Anyway, what version of PowerShell on Linux are you using, and how are you launching OMI and connecting? Can you post some copy-pastes of your commands?

**Comment by paulcallen** [comment] 2017-02-01 22:08
@energizedtech have you tried this with more recent versions of OMI/psl_omi_provider/powershell? The issues you are seeing should have been resolved some time ago.

**Comment by energizedtech** [comment] 2017-02-01 22:09
I'll fire up a Linux build tomorrow.   Been busy "Here/There/and Everywhere" but I caught the updated manifest :)


________________________________

**Comment by paulcallen** [comment] 2017-02-24 23:55
I am not aware of anyone seeing this at this point so I am going to close it. If you are still seeing this in newer builds then please re-active it.
Thanks

**Closed by paulcallen** 2017-02-24 23:55 UTC
