### ISSUE TITLE
Regression bug: PSRP client on Linux throws ERROR_WSMAN_SCHEMA_VALIDATION_ERROR when ConfigurationName is used.

### ISSUE THREAD

**Issue by bielawb** [PowerShell/psl-omi-provider#82] opened 2017-02-22 23:25 UTC
Opening the issue here, as requested by @SteveL-MSFT in PowerShell/PowerShell#3186

I'm trying to use psl-omi-provider (client) to connect from **Linux to Windows**.
It works fine on any version I've tried (alpha 14-16) if I use default configuration (not using `ConfigurationName` parameter). 

When I use this parameter in alpha 14 it also works fine. Unfortunately, both alpha 15 and 16 will report issue with schema:
```powershell
$ps2 = New-PSSession -ComputerName jumpbox -Credential $cred -Authentication basic -ConfigurationName DnsAdminRole

New-PSSession : [jumpbox] Connecting to remote server jumpbox failed with the following error message : 
ERROR_WSMAN_SCHEMA_VALIDATION_ERROR: The SOAP XML in the message does not match the corresponding XML schema definition. 
Change the XML and retry.  For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:8
+ $ps2 = New-PSSession -ComputerName jumpbox -Credential $cred -Authent ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : 1,PSSessionOpenFailed
```

**Comment by paulcallen** [comment] 2017-02-24 23:53
This is a duplicate of #71 which has been fixed, but we have not dropped new binaries to powershell yet. We are finalizing our testing and are hoping to drop the updated binaries to powershell some time next week

**Closed by paulcallen** 2017-02-24 23:53 UTC

**Comment by bielawb** [comment] 2017-02-27 20:54
Thanks. Looking forward to be able to getting it in the package.
Meanwhile simple workaround: specify full ConfigurationName instead of shortened version:

```powershell
$name = 'http://schemas.microsoft.com/powershell/DnsAdminRole'
$ps = New-PSSession -ComputerName jumpbox -Authentication basic -Credential $cred -ConfigurationName $name
$ps.ConfigurationName
DnsAdmin
```
